export const buildings = [
    //食堂・カフェ
  {
    id: "muscat",
    name: "マスカットユニオン",
    category: "cafeterria",
    type: "floor_text", 
    icon_size: "big",
    image: "images/muscat.jpg",
    coordinate: [34.68943,133.92047],
    floors: [
      { floor: "1F",
        items: ['ブックストア'] },
      { floor: "2F",
        items: ['学食'] },
      { floor: "3F",
        items: ['学食'] }
    ]
  },
  {
    id: "pione",
    name: "ピオーネユニオン",
    category: "cafeterria",
    type: "floor_text", 
    icon_size: "big",
    image: "images/pione.jpg",
    coordinate: [34.68934,133.92440],
    floors: [
      { floor: "1F",
        items: ['ショップ']},
      { floor: "2F",
        items: ['学食']}
    ]
  },
  {
    id: "peach",
    name: "ピーチユニオン",
    category: "cafeterria",
    type: "floor_text", 
    icon_size: "big",
    image: "images/peach.jpg",
    coordinate:[34.68731,133.92006],
    floors: [
      { floor: "1F",
        items: ['セブンイレブン','ピーチショップ']},
      { floor: "2F",
        items: ['学食']},
      { floor: "3F",
        items: ['学食']},
      { floor: "4F",
        items: ['レストラン']}
    ]
  },
  {
    id: "Uni_hall",
    name: "大学会館",
    category: "cafe",
    type: "floor_text",
    icon_size: "big", 
    image: "images/Uni_hall.jpg",
    coordinate:[34.68671,133.92052],
    floors: [
      { floor: "1F",
        items: ['喫茶 indent']}
    ]
  },
   {
    id: "J_cafe",
    name: "Junko Fukutake Terrace",
    category: "cafe",
    type: "floor_text", 
    icon_size: "big",
    image: "images/J_cafe.jpg",
    coordinate:[34.68526,133.91953],
    floors: [
      { floor: "1F",
        items: ['Junko Fukutake terrace'] }
    ]
  },
  //図書館
  {
    id: "library",
    name: "中央図書館",
    category: "library",
    type: "floor_text", 
    image: "images/library.jpg",
    coordinate:[34.68956,133.91961],
    floors: [
      { floor: "1F",
        items: ['図書館']}
    ]
  },
  //その他
  {
    id: "ShimizuGym",
    name: "清水記念体育館",
    category: "etc",
    type: "floor_text", 
    image: "images/ShimizuGym.jpg",
    coordinate:[34.68609, 133.92058],
  },
  {
    id: "Gym_2",
    name: "第二体育館",
    category: "etc",
    type: "floor_text", 
    image: "images/Gym_2.jpg",
    coordinate:[34.68550, 133.92018],
  },
  {
    id: "AnniversaryHall",
    name: "創立50周年記念館",
    category: "etc",
    type: "floor_text", 
    image: "images/AnniversaryHall.jpg",
    coordinate:[34.68723, 133.91864],
  },
  {
    id: "InfoCenter",
    name: "情報統括センター",
    category: "etc",
    type: "floor_text", 
    image: "images/InfoCenter.jpg",
    coordinate:[34.68996, 133.92054],
  },
  {
    id: "HeadBound",
    name: "本部棟",
    category: "etc",
    type: "floor_text", 
    image: "images/HeadBound.jpg",
    coordinate:[34.68679, 133.91862],
  },
  {
    id: "InternationalHall",
    name: "国際交流会館",
    category: "etc",
    type: "floor_text", 
    image: "images/InternationalHall.jpg",
    coordinate:[34.69045, 133.91932],
  },
  {
    id: "HospitalCenter",
    name: "保険管理センター",
    category: "etc",
    type: "floor_text", 
    image: "images/HospitalCenter.jpg",
    coordinate:[34.68738, 133.92075],
  },
  {
    id: "Incubator",
    name: "岡山大インキュベータ",
    category: "etc",
    type: "floor_text", 
    image: "images/incubator.jpg",
    coordinate:[34.68686, 133.91619],
  },
  {
    id: "TraSerCenter",
    name: "埋没文化財調査研究センター",
    category: "etc",
    type: "floor_text", 
    image: "images/TraSerCenter.jpg",
    coordinate:[34.69052, 133.92064],
  },
  //一般教育棟
  {
    id: "genEduBounds",
    name: "一般教育棟",
    category: "genEdu",
    icon_size: "big",
    type: "symbol", 
    coordinate:[34.68641,133.92206],
  },
  {
    id: "genEduBound_abc",
    name: "一般教育棟A・B・C棟",
    category: "genEdu",
    layerGroup: "genEdu",
    type: "floor_text", 
    image: "images/genEduBound_abc.jpg",
    coordinate:[34.68700,133.92200],
  },
  {
    id: "genEduBound_de",
    name: "一般教育棟D・E棟",
    category: "genEdu",
    layerGroup: "genEdu",
    type: "floor_text", 
    image: "images/genEduBound_de.jpg",
    coordinate:[34.68614,133.92194],
  },
  //工学部棟
  {
    id: "engSymbol",
    name: "工学部",
    category: "eng",
    icon_size: "big",
    type: "symbol", 
    coordinate:[34.68970,133.92253],
  },
  {
    id: "engBound_1",
    name: "工学部1号館",
    category: "eng",
    layerGroup: "eng",
    type: "floor_text",
    image: "images/engBound_1.jpg", 
    coordinate:[34.68968,133.92157],
  },
  {
    id: "engBound_2",
    name: "工学部2号館",
    category: "eng",
    layerGroup: "eng",
    type: "floor_text", 
    image: "images/engBound_2.jpg",
    coordinate:[34.68946,133.92258],
  },
  {
    id: "engBound_3",
    name: "工学部3号館",
    category: "eng",
    layerGroup: "eng",
    type: "floor_text", 
    image: "images/engBound_3.jpg",
    coordinate:[34.68988,133.92277],
  },
  {
    id: "engBound_4",
    name: "工学部4号館",
    category: "eng",
    layerGroup: "eng",
    type: "floor_text", 
    image: "images/engBound_4.jpg",
    coordinate:[34.69000,133.92339],
  },
  {
    id: "engBound_5",
    name: "工学部5号館",
    category: "eng",
    layerGroup: "eng",
    type: "floor_text", 
    image: "images/engBound_5.jpg",
    coordinate:[34.68976,133.92360],
  },
  {
    id: "engBound_6",
    name: "工学部6号館",
    category: "eng",
    layerGroup: "eng",
    type: "floor_text", 
    image: "images/engBound_6.jpg",
    coordinate:[34.68989,133.92437],
  },
  {
    id: "engBound_7",
    name: "工学部7号館",
    category: "eng",
    icon_size: "small",
    layerGroup: "eng",
    type: "floor_text", 
    image: "images/engBound_7.jpg",
    coordinate:[34.69011,133.92103],
  },
  {
    id: "engBound_8",
    name: "工学部8号館",
    category: "eng",
    icon_size: "small",
    layerGroup: "eng",
    type: "floor_text", 
    image: "images/engBound_8.jpg",
    coordinate:[34.69026,133.92152],
  },
  {
    id: "engBound_9",
    name: "工学部9号館",
    category: "eng",
    icon_size: "small",
    layerGroup: "eng",
    type: "floor_text", 
    image: "images/engBound_9.jpg",
    coordinate:[34.69018,133.92206],
  },
  {
    id: "engBound_10",
    name: "工学部10号館",
    category: "eng",
    icon_size: "small",
    layerGroup: "eng",
    type: "floor_text", 
    image: "images/engBound_10.jpg",
    coordinate:[34.69021,133.92252],
  },
  {
    id: "engBound_11",
    name: "工学部11号館",
    category: "eng",
    icon_size: "small",
    layerGroup: "eng",
    type: "floor_text", 
    image: "images/engBound_11.jpg",
   coordinate:[34.69018,133.92269],
  },
  {
    id: "engBound_12",
    name: "工学部12号館",
    category: "eng",
    icon_size: "small",
    layerGroup: "eng",
    type: "floor_text", 
    image: "images/engBound_12.jpg",
    coordinate:[34.69021,133.92294],
  },
  {
    id: "engBound_13",
    name: "工学部13号館",
    category: "eng",
    icon_size: "small",
    layerGroup: "eng",
    type: "floor_text", 
    image: "images/engBound_13.jpg",
    coordinate:[34.69023,133.92363],
  },
  {
    id: "engBound_14",
    name: "工学部14号館",
    category: "eng",
    icon_size: "small",
    layerGroup: "eng",
    type: "floor_text", 
    image: "images/engBound_14.jpg",
    coordinate:[34.69022,133.92393],
  },
  {
    id: "engBound_15",
    name: "旧工学部15号館",
    category: "eng",
    icon_size: "small",
    layerGroup: "eng",
    type: "floor_text", 
    image: "images/engBound_15.jpg",
    coordinate: [34.69018,133.92422],
  },
  {
    id: "engBound_16",
    name: "工学部16号館",
    category: "eng",
    icon_size: "small",
    layerGroup: "eng",
    type: "floor_text", 
    image: "images/engBound_16.jpg",
    coordinate: [34.69032,133.92438],
  },
  {
    id: "engBound_17",
    name: "工学部17号館",
    category: "eng",
    icon_size: "small",
    layerGroup: "eng",
    type: "floor_text", 
    image: "images/engBound_17.jpg",
    coordinate: [34.69055,133.92129],
  },
  {
    id: "engBound_18",
    name: "工学部18号館",
    category: "eng",
    icon_size: "small",
    layerGroup: "eng",
    type: "floor_text", 
    image: "images/engBound_18.jpg",
    coordinate: [34.69054,133.92145],
  },
  {
    id: "engBound_19",
    name: "工学部19号館",
    category: "eng",
    icon_size: "small",
    layerGroup: "eng",
    type: "floor_text", 
    image: "images/engBound_19.jpg",
    coordinate: [34.69054,133.92180],
  },
  {
    id: "engBound_20",
    name: "工学部20号館",
    category: "eng",
    icon_size: "small",
    layerGroup: "eng",
    type: "floor_text", 
    image: "images/engBound_20.jpg",
    coordinate: [34.69054,133.92217],
  },
  {
    id: "engBound_21",
    name: "工学部21号館",
    category: "eng",
    icon_size: "small",
    layerGroup: "eng",
    type: "floor_text", 
    image: "images/engBound_21.jpg",
    coordinate: [34.69061,133.92295],
  },
  {
    id: "engSer",
    name: "工学部実験研究棟",
    category: "eng",
    icon_size: "small",
    layerGroup: "eng",
    type: "floor_text", 
    image: "images/engSer.jpg",
    coordinate: [34.69063,133.92401],
  },
  {
    id: "engNatRes",
    name: "自然科学系総合研究棟",
    category: "eng",
    layerGroup: "eng",
    type: "floor_text", 
    image: "images/engNat.jpg",
    coordinate: [34.68947,133.92313],
  },
  {
    id: "engCommons",
    name: "共育共創コモンズ",
    category: "eng",
    layerGroup: "eng",
    type: "floor_text", 
    image: "images/engCommons.jpg",
    coordinate: [34.68940,133.92387],
  },
  {
    id: "engEnvBound",
    name: "環境理工棟",
    category: "eng",
    layerGroup: "eng",
    type: "floor_text", 
    image: "images/engEnv.jpg",
    coordinate: [34.68974,133.92505],
  },
  {
    id: "engNewTechCenter",
    name: "新技術センター",
    category: "eng",
    layerGroup: "eng",
    type: "floor_text", 
    image: "images/engNewTechCenter.jpg",
    coordinate: [34.68971, 133.92642],
  },
  //理学部
  {
    id: "sciSymbol",
    name: "理学部",
    category: "sci",
    icon_size: "big",
    type: "symbol", 
    coordinate: [34.68848,133.92160],
  },
  {
    id: "sciBound_main",
    name: "理学部本館",
    category: "sci",
    layerGroup: "sci",
    type: "floor_text",
    image: "images/sciBound_main.jpg", 
    coordinate: [34.68845,133.92025],
  },
  {
    id: "sciBound_2",
    name: "理学部2号館",
    category: "sci",
    layerGroup: "sci",
    type: "floor_text",
    image: "images/sciBound_2.jpg", 
    coordinate: [34.68868,133.92187],
  },
  {
    id: "sciCollabo",
    name: "コラボレーション棟",
    category: "sci",
    layerGroup: "sci",
    type: "floor_text",
    image: "images/sciCollabo.jpg", 
    coordinate: [34.68826,133.92146],
  },
  {
    id: "sciNatRes",
    name: "自然科学研究科棟",
    category: "sci",
    layerGroup: "sci",
    type: "floor_text",
    image: "images/sciNatRes.jpg", 
    coordinate: [34.68864,133.92277],
  },
  {
    id: "sciIntRes",
    name: "異分野基礎科学研究所棟",
    category: "sci",
    layerGroup: "sci",
    type: "floor_text",
    image: "images/sciIntRes.jpg", 
    coordinate: [34.68827,133.92199],
  },
  {
    id: "sciLifeSupp",
    name: "附属自然生命科学研究支援センター",
    category: "sci",
    layerGroup: "sci",
    type: "floor_text",
    image: "images/sciLifeSupp.jpg", 
    coordinate: [34.68820,133.92280],
  },
  {
    id: "sciInnoLab",
    name: "共創イノベーションラボ",
    category: "sci",
    layerGroup: "sci",
    type: "floor_text",
    image: "images/sciInnoLab.jpg", 
    coordinate: [34.68848,133.92287],
  },
  //文・法・経学部
  {
    id: "humSymbol",
    name: "文学部",
    category: "hum",
    icon_size: "big",
    type: "symbol", 
    coordinate: [34.68927,133.91846],
  },
  {
    id: "humCulRes",
    name: "文化科学系研究棟",
    category: "hum",
    layerGroup: "hum",
    type: "floor_text",
    image: "images/humCulRes.jpg", 
    coordinate: [34.68813,133.91854],
  },
  {
    id: "humBound_1",
    name: "文法経1号館",
    category: "hum",
    layerGroup: "hum",
    type: "floor_text",
    image: "images/humBound_1.jpg", 
    coordinate: [34.68895,133.91833],
  },
  {
    id: "humBound_2",
    name: "文法経2号館",
    category: "hum",
    layerGroup: "hum",
    type: "floor_text",
    image: "images/humBound_2.jpg", 
    coordinate: [34.68847,133.91836],
  },
  {
    id: "humLec",
    name: "文法経講義棟",
    category: "hum",
    layerGroup: "hum",
    type: "floor_text",
    image: "images/humLec.jpg", 
    coordinate: [34.68954,133.91862],
  },
  {
    id: "humArcRoom",
    name: "文学部考古学資料室",
    category: "hum",
    layerGroup: "hum",
    type: "floor_text",
    image: "images/humArcRoom.jpg", 
    coordinate: [34.68998,133.91855],
  },
  //農学部
  {
    id: "agrSymbol",
    name: "農学部",
    category: "agr",
    icon_size: "big",
    type: "symbol", 
    coordinate: [34.68597,133.91801],
  },
  {
    id: "agrBound_1",
    name: "農学部1号館",
    category: "agr",
    layerGroup: "agr",
    type: "floor_text",
    image: "images/agrBound_1.jpg", 
    coordinate: [34.68596,133.91886],
  },
  {
    id: "agrBound_2",
    name: "農学部2号館",
    category: "agr",
    layerGroup: "agr",
    type: "floor_text",
    image: "images/agrBound_2.jpg", 
    coordinate: [34.68570,133.91761],
  },
  {
    id: "agrBound_3",
    name: "農学部3号館",
    category: "agr",
    layerGroup: "agr",
    type: "floor_text",
    image: "images/agrBound_3.jpg", 
    coordinate: [34.68611,133.91762],
  },
  {
    id: "agrBound_4",
    name: "農学部4号館",
    category: "agr",
    layerGroup: "agr",
    type: "floor_text",
    image: "images/agrBound_4.jpg", 
    coordinate: [34.68522,133.91410],
  },
  //教育学部
  {
    id: "eduSymbol",
    name: "教育学部",
    category: "edu",
    icon_size: "big",
    type: "symbol", 
    coordinate: [34.68870,133.92497],
  },
  {
    id: "eduBound_main",
    name: "教育学部本館",
    category: "edu",
    layerGroup: "edu",
    type: "floor_text",
    image: "images/eduBound_main.jpg", 
    coordinate: [34.68871,133.92419],
  },
  {
    id: "eduLec",
    name: "教育学部講義棟",
    category: "edu",
    layerGroup: "edu",
    type: "floor_text",
    image: "images/eduLec.jpg", 
    coordinate: [34.68816,133.92421],
  },
  {
    id: "eduEas",
    name: "教育学部東棟",
    category: "edu",
    layerGroup: "edu",
    type: "floor_text",
    image: "images/eduEas.jpg", 
    coordinate: [34.68853,133.92565],
  },
  {
    id: "eduGym",
    name: "教育学部体育棟",
    category: "edu",
    layerGroup: "edu",
    type: "floor_text",
    image: "images/eduGym.jpg", 
    coordinate: [34.68894,133.92548],
  },
  {
    id: "eduNorMus",
    name: "教育学部北音楽棟",
    category: "edu",
    layerGroup: "edu",
    type: "floor_text",
    image: "images/eduNorMus.jpg", 
    coordinate: [34.68852, 133.92645],
  },
  {
    id: "eduSouMus",
    name: "教育学部南音楽棟",
    category: "edu",
    layerGroup: "edu",
    type: "floor_text",
    image: "images/eduSouMus.jpg", 
    coordinate: [34.68818, 133.92638],
  },
  //薬学部
  {
    id: "phaSymbol",
    name: "薬学部",
    category: "pha",
    icon_size: "big",
    type: "symbol", 
    coordinate: [34.68710,133.91722],
  },
  {
    id: "phaBound_1",
    name: "薬学部1号館",
    category: "pha",
    layerGroup: "pha",
    type: "floor_text",
    image: "images/phaBound_1.jpg", 
    coordinate: [34.68703,133.91754],
  },
  {
    id: "phaBound_2",
    name: "薬学部2号館",
    category: "pha",
    layerGroup: "pha",
    type: "floor_text",
    image: "images/phaBound_2.jpg", 
    coordinate: [34.68715,133.91696],
  },
  {
    id: "phaHerbGarden",
    name: "薬用植物園",
    category: "pha",
    layerGroup: "pha",
    type: "floor_text",
    image: "images/phaHerbGarden.jpg", 
    coordinate: [34.68731,133.91651],
  }
];