export const buildings = [
    //食堂・カフェ
  {
    id: "muscat",
    name: "マスカットユニオン",
    category: "cafeterria",
    type: "floor_text", 
    image: "images/muscat.jpg",
    lat: 34.68943,
    lng: 133.92047,
    floors: [
      { floor: "1F",
        items: ['ブックストア'] },
      { floor: "2F",
        items: ['学食'] },
      { floor: "3F",
        items: ['学食'] }
    ]
  },
  {
    id: "pione",
    name: "ピオーネユニオン",
    category: "cafeterria",
    type: "floor_text", 
    image: "images/pione.jpg",
    lat: 34.68934,
    lng: 133.92440,
    floors: [
      { floor: "1F",
        items: ['ショップ']},
      { floor: "2F",
        items: ['学食']}
    ]
  },
  {
    id: "peach",
    name: "ピーチユニオン",
    category: "cafeterria",
    type: "floor_text", 
    image: "images/peach.jpg",
    lat: 34.68731,
    lng: 133.92006,
    floors: [
      { floor: "1F",
        items: ['セブンイレブン','ピーチショップ']},
      { floor: "2F",
        items: ['学食']},
      { floor: "3F",
        items: ['学食']},
      { floor: "4F",
        items: ['レストラン']}
    ]
  },
  {
    id: "Uni_hall",
    name: "大学会館",
    category: "cafe",
    type: "floor_text", 
    image: "images/Uni_hall.jpg",
    lat: 34.68671,
    lng: 133.92052,
    floors: [
      { floor: "1F",
        items: ['喫茶 indent']}
    ]
  },
   {
    id: "J_cafe",
    name: "Junko Fukutake Terrace",
    category: "cafe",
    type: "floor_text", 
    image: "images/J_cafe.jpg",
    lat: 34.68526,
    lng: 133.91953,
    floors: [
      { floor: "1F",
        items: ['Junko Fukutake terrace'] }
    ]
  },
  //図書館
  {
    id: "library",
    name: "中央図書館",
    category: "library",
    type: "floor_text", 
    image: "images/library.jpg",
    lat: 34.68955,
    lng: 133.91983,
    floors: [
      { floor: "1F",
        items: ['図書館']}
    ]
  },
  //一般教育棟
  {
    id: "genEduBounds",
    name: "一般教育棟",
    category: "genEdu",
    icon_size: "big",
    type: "symbol", 
    lat: 34.68641,
    lng: 133.92206,
  },
  {
    id: "genEduBound_abc",
    name: "一般教育棟A・B・C棟",
    category: "genEdu",
    layerGroup: "genEdu",
    type: "floor_text", 
    lat: 34.68700,
    lng: 133.92200,
  },
  {
    id: "genEduBound_de",
    name: "一般教育棟D・E棟",
    category: "genEdu",
    layerGroup: "genEdu",
    type: "floor_text", 
    lat: 34.68614,
    lng: 133.92194,
  },
  //工学部棟
  {
    id: "engSymbol",
    name: "工学部",
    category: "eng",
    icon_size: "big",
    type: "symbol", 
    lat: 34.68970,
    lng: 133.92253,
  },
  {
    id: "engBound_1",
    name: "工学部1号館",
    category: "eng",
    layerGroup: "eng",
    type: "floor_text",
    image: "images/engBound_1.jpg", 
    lat: 34.68968,
    lng: 133.92157,
  },
  {
    id: "engBound_2",
    name: "工学部2号館",
    category: "eng",
    layerGroup: "eng",
    type: "floor_text", 
    image: "images/engBound_2.jpg",
    lat: 34.68946,
    lng: 133.92258,
  },
  {
    id: "engBound_3",
    name: "工学部3号館",
    category: "eng",
    layerGroup: "eng",
    type: "floor_text", 
    image: "images/engBound_3.jpg",
    lat: 34.68988,
    lng: 133.92277,
  },
  {
    id: "engBound_4",
    name: "工学部4号館",
    category: "eng",
    layerGroup: "eng",
    type: "floor_text", 
    image: "images/engBound_4.jpg",
    lat: 34.69000,
    lng: 133.92339,
  },
  {
    id: "engBound_5",
    name: "工学部5号館",
    category: "eng",
    layerGroup: "eng",
    type: "floor_text", 
    image: "images/engBound_5.jpg",
    lat: 34.68976,
    lng: 133.92360,
  },
  {
    id: "engBound_6",
    name: "工学部6号館",
    category: "eng",
    layerGroup: "eng",
    type: "floor_text", 
    image: "images/engBound_6.jpg",
    lat: 34.68989,
    lng: 133.92437,
  },
  {
    id: "engBound_7",
    name: "工学部7号館",
    category: "eng",
    icon_size: "small",
    layerGroup: "eng",
    type: "floor_text", 
    image: "images/engBound_7.jpg",
    lat: 34.69011,
    lng: 133.92103,
  },
  {
    id: "engBound_8",
    name: "工学部8号館",
    category: "eng",
    icon_size: "small",
    layerGroup: "eng",
    type: "floor_text", 
    image: "images/engBound_8.jpg",
    lat: 34.69026,
    lng: 133.92152,
  },
  {
    id: "engBound_9",
    name: "工学部9号館",
    category: "eng",
    icon_size: "small",
    layerGroup: "eng",
    type: "floor_text", 
    image: "images/engBound_9.jpg",
    lat: 34.69018,
    lng: 133.92206,
  },
  {
    id: "engBound_10",
    name: "工学部10号館",
    category: "eng",
    icon_size: "small",
    layerGroup: "eng",
    type: "floor_text", 
    image: "images/engBound_10.jpg",
    lat: 34.69021,
    lng: 133.92252,
  },
  {
    id: "engBound_11",
    name: "工学部11号館",
    category: "eng",
    icon_size: "small",
    layerGroup: "eng",
    type: "floor_text", 
    image: "images/engBound_11.jpg",
    lat: 34.69018,
    lng: 133.92269,
  },
  {
    id: "engBound_12",
    name: "工学部12号館",
    category: "eng",
    icon_size: "small",
    layerGroup: "eng",
    type: "floor_text", 
    image: "images/engBound_12.jpg",
    lat: 34.69021,
    lng: 133.92294,
  },
  {
    id: "engBound_13",
    name: "工学部13号館",
    category: "eng",
    icon_size: "small",
    layerGroup: "eng",
    type: "floor_text", 
    image: "images/engBound_13.jpg",
    lat: 34.69023,
    lng: 133.92363,
  },
  {
    id: "engBound_14",
    name: "工学部14号館",
    category: "eng",
    icon_size: "small",
    layerGroup: "eng",
    type: "floor_text", 
    image: "images/engBound_14.jpg",
    lat: 34.69022,
    lng: 133.92393,
  },
  {
    id: "engBound_15",
    name: "旧工学部15号館",
    category: "eng",
    icon_size: "small",
    layerGroup: "eng",
    type: "floor_text", 
    image: "images/engBound_15.jpg",
    lat: 34.69018,
    lng: 133.92422,
  },
  {
    id: "engBound_16",
    name: "工学部16号館",
    category: "eng",
    icon_size: "small",
    layerGroup: "eng",
    type: "floor_text", 
    image: "images/engBound_16.jpg",
    lat: 34.69032,
    lng: 133.92438,
  },
  {
    id: "engBound_17",
    name: "工学部17号館",
    category: "eng",
    icon_size: "small",
    layerGroup: "eng",
    type: "floor_text", 
    image: "images/engBound_17.jpg",
    lat: 34.69055,
    lng: 133.92129,
  },
  {
    id: "engBound_18",
    name: "工学部18号館",
    category: "eng",
    icon_size: "small",
    layerGroup: "eng",
    type: "floor_text", 
    image: "images/engBound_18.jpg",
    lat: 34.69054,
    lng: 133.92145,
  },
  {
    id: "engBound_19",
    name: "工学部19号館",
    category: "eng",
    icon_size: "small",
    layerGroup: "eng",
    type: "floor_text", 
    image: "images/engBound_19.jpg",
    lat: 34.69054,
    lng: 133.92180,
  },
  {
    id: "engBound_20",
    name: "工学部20号館",
    category: "eng",
    icon_size: "small",
    layerGroup: "eng",
    type: "floor_text", 
    image: "images/engBound_20.jpg",
    lat: 34.69054,
    lng: 133.92217,
  },
  {
    id: "engNatRes",
    name: "自然科学系総合研究棟",
    category: "eng",
    layerGroup: "eng",
    type: "floor_text", 
    image: "images/engNat.jpg",
    lat: 34.68947,
    lng: 133.92313,
  },
  {
    id: "engCommons",
    name: "共育共創コモンズ",
    category: "eng",
    layerGroup: "eng",
    type: "floor_text", 
    image: "images/engCommons.jpg",
    lat: 34.68940,
    lng: 133.92387,
  },
  {
    id: "engEnvBound",
    name: "環境理工棟",
    category: "eng",
    layerGroup: "eng",
    type: "floor_text", 
    image: "images/engEnv.jpg",
    lat: 34.68974,
    lng: 133.92505,
  },
  //理学部
  {
    id: "sciSymbol",
    name: "理学部",
    category: "sci",
    icon_size: "big",
    type: "symbol", 
    lat: 34.68848,
    lng: 133.92160,
  },
  {
    id: "sciBound_main",
    name: "理学部本館",
    category: "sci",
    layerGroup: "sci",
    type: "floor_text",
    image: "images/sciBound_main.jpg", 
    lat: 34.68845,
    lng: 133.92025,
  },
  {
    id: "sciBound_2",
    name: "理学部2号館",
    category: "sci",
    layerGroup: "sci",
    type: "floor_text",
    image: "images/sciBound_2.jpg", 
    lat: 34.68868,
    lng: 133.92187,
  },
  {
    id: "sciCollabo",
    name: "コラボレーション棟",
    category: "sci",
    layerGroup: "sci",
    type: "floor_text",
    image: "images/sciCollabo.jpg", 
    lat: 34.68826,
    lng: 133.92146,
  },
  {
    id: "sciNatRes",
    name: "自然科学研究科棟",
    category: "sci",
    layerGroup: "sci",
    type: "floor_text",
    image: "images/sciNatRes.jpg", 
    lat: 34.68864,
    lng: 133.92277,
  },
  {
    id: "sciIntRes",
    name: "異分野基礎科学研究所棟",
    category: "sci",
    layerGroup: "sci",
    type: "floor_text",
    image: "images/sciIntRes.jpg", 
    lat: 34.68827,
    lng: 133.92199,
  },
  {
    id: "sciLifeSupp",
    name: "附属自然生命科学研究支援センター",
    category: "sci",
    layerGroup: "sci",
    type: "floor_text",
    image: "images/sciLifeSupp.jpg", 
    lat: 34.68820,
    lng: 133.92280,
  },
  {
    id: "sciInnoLab",
    name: "共創イノベーションラボ",
    category: "sci",
    layerGroup: "sci",
    type: "floor_text",
    image: "images/sciInnoLab.jpg", 
    lat: 34.68848,
    lng: 133.92287,
  },
  {
    id: "sciInnoLab",
    name: "共創イノベーションラボ",
    category: "sci",
    layerGroup: "sci",
    type: "floor_text",
    image: "images/sciInnoLab.jpg", 
    lat: 34.68848,
    lng: 133.92287,
  },
  //文・法・経学部
  {
    id: "humSymbol",
    name: "文学部",
    category: "hum",
    icon_size: "big",
    type: "symbol", 
    lat: 34.68988,
    lng: 133.91866,
  },
  {
    id: "humCulRes",
    name: "文化科学系研究棟",
    category: "hum",
    layerGroup: "hum",
    type: "floor_text",
    image: "images/humCulRes.jpg", 
    lat: 34.68952,
    lng: 133.91849,
  },
  {
    id: "humBound_1",
    name: "文法経1号館",
    category: "hum",
    layerGroup: "hum",
    type: "floor_text",
    image: "images/humBound_1.jpg", 
    lat: 34.68976,
    lng: 133.91874,
  },
  {
    id: "humBound_2",
    name: "文法経2号館",
    category: "hum",
    layerGroup: "hum",
    type: "floor_text",
    image: "images/humBound_2.jpg", 
    lat: 34.68966,
    lng: 133.91869,
  },
  {
    id: "humlec",
    name: "文法経講義棟",
    category: "hum",
    layerGroup: "hum",
    type: "floor_text",
    image: "images/humlec.jpg", 
    lat: 34.68998,
    lng: 133.91855,
  },
  {
    id: "humArcRoom",
    name: "文学部考古学資料室",
    category: "hum",
    layerGroup: "hum",
    type: "floor_text",
    image: "images/humArcRoom.jpg", 
    lat: 34.69015,
    lng: 133.91875,
  }
];